### ISSUE TITLE
add fennel loader to rockspec file

### ISSUE THREAD

**Issue by erikLundstedt** [DarkWiiPlayer/glass#2]
as the title

I see you added a loader for fennel files, but you forgot to add it to the list of files in the rockspec

**Comment by erikLundstedt** [comment]
```lua
		["glass.fennel"] = "glass/fennel.lua",
```
will do it

**Comment by DarkWiiPlayer** [comment]
Fixed :)

**Comment by erikLundstedt** [comment]
thanks

I`m gonna play around some with your implementation of the fennel loader, I see you implemented it differently than me
